/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NonauthedRouteImport } from './routes/_nonauthed'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as NonauthedIndexRouteImport } from './routes/_nonauthed/index'
import { Route as ApiOtpLatestRouteImport } from './routes/api/otp-latest'
import { Route as NonauthedSignupRouteImport } from './routes/_nonauthed/signup'
import { Route as NonauthedLoginRequestCodeRouteImport } from './routes/_nonauthed/login-request-code'
import { Route as NonauthedLoginPasskeyRouteImport } from './routes/_nonauthed/login-passkey'
import { Route as NonauthedLoginAccountPasskeyRouteImport } from './routes/_nonauthed/login-account-passkey'
import { Route as NonauthedLoginRouteImport } from './routes/_nonauthed/login'
import { Route as AuthedUserSettingsRouteImport } from './routes/_authed/user-settings'
import { Route as AuthedLogoutRouteImport } from './routes/_authed/logout'
import { Route as NonauthedSignupVerifySignupTokenRouteImport } from './routes/_nonauthed/signup-verify.$signupToken'
import { Route as NonauthedLoginViaCodeCodeVerificationTokenRouteImport } from './routes/_nonauthed/login-via-code.$codeVerificationToken'

const NonauthedRoute = NonauthedRouteImport.update({
  id: '/_nonauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const NonauthedIndexRoute = NonauthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NonauthedRoute,
} as any)
const ApiOtpLatestRoute = ApiOtpLatestRouteImport.update({
  id: '/api/otp-latest',
  path: '/api/otp-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const NonauthedSignupRoute = NonauthedSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => NonauthedRoute,
} as any)
const NonauthedLoginRequestCodeRoute =
  NonauthedLoginRequestCodeRouteImport.update({
    id: '/login-request-code',
    path: '/login-request-code',
    getParentRoute: () => NonauthedRoute,
  } as any)
const NonauthedLoginPasskeyRoute = NonauthedLoginPasskeyRouteImport.update({
  id: '/login-passkey',
  path: '/login-passkey',
  getParentRoute: () => NonauthedRoute,
} as any)
const NonauthedLoginAccountPasskeyRoute =
  NonauthedLoginAccountPasskeyRouteImport.update({
    id: '/login-account-passkey',
    path: '/login-account-passkey',
    getParentRoute: () => NonauthedRoute,
  } as any)
const NonauthedLoginRoute = NonauthedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NonauthedRoute,
} as any)
const AuthedUserSettingsRoute = AuthedUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogoutRoute = AuthedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthedRoute,
} as any)
const NonauthedSignupVerifySignupTokenRoute =
  NonauthedSignupVerifySignupTokenRouteImport.update({
    id: '/signup-verify/$signupToken',
    path: '/signup-verify/$signupToken',
    getParentRoute: () => NonauthedRoute,
  } as any)
const NonauthedLoginViaCodeCodeVerificationTokenRoute =
  NonauthedLoginViaCodeCodeVerificationTokenRouteImport.update({
    id: '/login-via-code/$codeVerificationToken',
    path: '/login-via-code/$codeVerificationToken',
    getParentRoute: () => NonauthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NonauthedIndexRoute
  '/logout': typeof AuthedLogoutRoute
  '/user-settings': typeof AuthedUserSettingsRoute
  '/login': typeof NonauthedLoginRoute
  '/login-account-passkey': typeof NonauthedLoginAccountPasskeyRoute
  '/login-passkey': typeof NonauthedLoginPasskeyRoute
  '/login-request-code': typeof NonauthedLoginRequestCodeRoute
  '/signup': typeof NonauthedSignupRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/login-via-code/$codeVerificationToken': typeof NonauthedLoginViaCodeCodeVerificationTokenRoute
  '/signup-verify/$signupToken': typeof NonauthedSignupVerifySignupTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof NonauthedIndexRoute
  '/logout': typeof AuthedLogoutRoute
  '/user-settings': typeof AuthedUserSettingsRoute
  '/login': typeof NonauthedLoginRoute
  '/login-account-passkey': typeof NonauthedLoginAccountPasskeyRoute
  '/login-passkey': typeof NonauthedLoginPasskeyRoute
  '/login-request-code': typeof NonauthedLoginRequestCodeRoute
  '/signup': typeof NonauthedSignupRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/login-via-code/$codeVerificationToken': typeof NonauthedLoginViaCodeCodeVerificationTokenRoute
  '/signup-verify/$signupToken': typeof NonauthedSignupVerifySignupTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_nonauthed': typeof NonauthedRouteWithChildren
  '/_authed/logout': typeof AuthedLogoutRoute
  '/_authed/user-settings': typeof AuthedUserSettingsRoute
  '/_nonauthed/login': typeof NonauthedLoginRoute
  '/_nonauthed/login-account-passkey': typeof NonauthedLoginAccountPasskeyRoute
  '/_nonauthed/login-passkey': typeof NonauthedLoginPasskeyRoute
  '/_nonauthed/login-request-code': typeof NonauthedLoginRequestCodeRoute
  '/_nonauthed/signup': typeof NonauthedSignupRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/_nonauthed/': typeof NonauthedIndexRoute
  '/_nonauthed/login-via-code/$codeVerificationToken': typeof NonauthedLoginViaCodeCodeVerificationTokenRoute
  '/_nonauthed/signup-verify/$signupToken': typeof NonauthedSignupVerifySignupTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/user-settings'
    | '/login'
    | '/login-account-passkey'
    | '/login-passkey'
    | '/login-request-code'
    | '/signup'
    | '/api/otp-latest'
    | '/login-via-code/$codeVerificationToken'
    | '/signup-verify/$signupToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/user-settings'
    | '/login'
    | '/login-account-passkey'
    | '/login-passkey'
    | '/login-request-code'
    | '/signup'
    | '/api/otp-latest'
    | '/login-via-code/$codeVerificationToken'
    | '/signup-verify/$signupToken'
  id:
    | '__root__'
    | '/_authed'
    | '/_nonauthed'
    | '/_authed/logout'
    | '/_authed/user-settings'
    | '/_nonauthed/login'
    | '/_nonauthed/login-account-passkey'
    | '/_nonauthed/login-passkey'
    | '/_nonauthed/login-request-code'
    | '/_nonauthed/signup'
    | '/api/otp-latest'
    | '/_nonauthed/'
    | '/_nonauthed/login-via-code/$codeVerificationToken'
    | '/_nonauthed/signup-verify/$signupToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  NonauthedRoute: typeof NonauthedRouteWithChildren
  ApiOtpLatestRoute: typeof ApiOtpLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_nonauthed': {
      id: '/_nonauthed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NonauthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nonauthed/': {
      id: '/_nonauthed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NonauthedIndexRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/api/otp-latest': {
      id: '/api/otp-latest'
      path: '/api/otp-latest'
      fullPath: '/api/otp-latest'
      preLoaderRoute: typeof ApiOtpLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nonauthed/signup': {
      id: '/_nonauthed/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof NonauthedSignupRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_nonauthed/login-request-code': {
      id: '/_nonauthed/login-request-code'
      path: '/login-request-code'
      fullPath: '/login-request-code'
      preLoaderRoute: typeof NonauthedLoginRequestCodeRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_nonauthed/login-passkey': {
      id: '/_nonauthed/login-passkey'
      path: '/login-passkey'
      fullPath: '/login-passkey'
      preLoaderRoute: typeof NonauthedLoginPasskeyRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_nonauthed/login-account-passkey': {
      id: '/_nonauthed/login-account-passkey'
      path: '/login-account-passkey'
      fullPath: '/login-account-passkey'
      preLoaderRoute: typeof NonauthedLoginAccountPasskeyRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_nonauthed/login': {
      id: '/_nonauthed/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NonauthedLoginRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_authed/user-settings': {
      id: '/_authed/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AuthedUserSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logout': {
      id: '/_authed/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthedLogoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_nonauthed/signup-verify/$signupToken': {
      id: '/_nonauthed/signup-verify/$signupToken'
      path: '/signup-verify/$signupToken'
      fullPath: '/signup-verify/$signupToken'
      preLoaderRoute: typeof NonauthedSignupVerifySignupTokenRouteImport
      parentRoute: typeof NonauthedRoute
    }
    '/_nonauthed/login-via-code/$codeVerificationToken': {
      id: '/_nonauthed/login-via-code/$codeVerificationToken'
      path: '/login-via-code/$codeVerificationToken'
      fullPath: '/login-via-code/$codeVerificationToken'
      preLoaderRoute: typeof NonauthedLoginViaCodeCodeVerificationTokenRouteImport
      parentRoute: typeof NonauthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedLogoutRoute: typeof AuthedLogoutRoute
  AuthedUserSettingsRoute: typeof AuthedUserSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLogoutRoute: AuthedLogoutRoute,
  AuthedUserSettingsRoute: AuthedUserSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface NonauthedRouteChildren {
  NonauthedLoginRoute: typeof NonauthedLoginRoute
  NonauthedLoginAccountPasskeyRoute: typeof NonauthedLoginAccountPasskeyRoute
  NonauthedLoginPasskeyRoute: typeof NonauthedLoginPasskeyRoute
  NonauthedLoginRequestCodeRoute: typeof NonauthedLoginRequestCodeRoute
  NonauthedSignupRoute: typeof NonauthedSignupRoute
  NonauthedIndexRoute: typeof NonauthedIndexRoute
  NonauthedLoginViaCodeCodeVerificationTokenRoute: typeof NonauthedLoginViaCodeCodeVerificationTokenRoute
  NonauthedSignupVerifySignupTokenRoute: typeof NonauthedSignupVerifySignupTokenRoute
}

const NonauthedRouteChildren: NonauthedRouteChildren = {
  NonauthedLoginRoute: NonauthedLoginRoute,
  NonauthedLoginAccountPasskeyRoute: NonauthedLoginAccountPasskeyRoute,
  NonauthedLoginPasskeyRoute: NonauthedLoginPasskeyRoute,
  NonauthedLoginRequestCodeRoute: NonauthedLoginRequestCodeRoute,
  NonauthedSignupRoute: NonauthedSignupRoute,
  NonauthedIndexRoute: NonauthedIndexRoute,
  NonauthedLoginViaCodeCodeVerificationTokenRoute:
    NonauthedLoginViaCodeCodeVerificationTokenRoute,
  NonauthedSignupVerifySignupTokenRoute: NonauthedSignupVerifySignupTokenRoute,
}

const NonauthedRouteWithChildren = NonauthedRoute._addFileChildren(
  NonauthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  NonauthedRoute: NonauthedRouteWithChildren,
  ApiOtpLatestRoute: ApiOtpLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
