name: Deploy demo to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy demo to Cloud Run
    runs-on: ubuntu-latest
    env:
      GAR_HOSTNAME: us-central1-docker.pkg.dev # Artifact Registry hostname
      PROJECT_ID: bhouston-general-hosting # Your GCP project ID
      REGION: us-central1 # Cloud Run region
      SERVICE: passwordless # Cloud Run service name
      DOCKER_REGISTRY: shared-docker-registry
      SITE_URL: https://passwordless.ben3d.ca
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          skip_install: true

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_HOSTNAME }}

      - name: Set image path
        id: image
        run: echo "image_path=${{ env.GAR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.DOCKER_REGISTRY }}/${{ env.SERVICE }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.image.outputs.image_path }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ steps.image.outputs.image_path }}
          flags: '--allow-unauthenticated --set-env-vars=JWT_SECRET=${{ secrets.JWT_SECRET }},SITE_URL=${{ env.SITE_URL }}'
